server:
  port: 8001
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/medi_care_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 20 # 最大连接数
      minimum-idle: 5 # 最小空闲连接数
      idle-timeout: 30000 # 连接超时时间 30000是30秒
      max-lifetime: 1800000 # 连接最大空闲时间 1800000是30分钟
      connection-timeout: 30000 # 连接超时时间 30000是30秒

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台打印SQL
    map-underscore-to-camel-case: true # 开启下划线转驼峰
  global-config:
    db-config:
      id-type: assign_id # 雪花算法ID (生成一个全局唯一的长整型 ID)
  mapper-locations: classpath*:mapper/*.xml

# Swagger 配置 (这是 SpringDoc OpenAPI 框架的配置，用于定制 Swagger 文档的访问路径)
springdoc:
  enabled: true
  api-docs:
    path: /v3/api-docs #定义 OpenAPI 3.0 规范文档（JSON 格式）的访问地址。
  swagger-ui:
    enabled: true
    display-request-duration: true
    display-operation-id: true
    path: /swagger-ui.html #定义 Swagger UI 的 HTML 页面入口地址。
  packages-to-scan: com.mediacare.user.controller # 默认包扫描
  default-flat-param-object: true   #避免参数嵌套混乱

# 日志级别
logging:
  level:
    com.mediacare: debug



jwt:
  secret-key: yiJU6i33Da4J1r6MuiD2I9TMk3A1nrxnieRFmoja5kU= # 环境变量优先
  expiration: 7200 # 单位：秒